server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: oris_spring
  datasource:
    url: 'jdbc:postgresql://localhost:5432/oris_spring'
    username: postgres
    password: Fadc766e!
    driverClassName: org.postgresql.Driver